import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";
import "../styles/global.scss";

const inter = Schibsted_Grotesk({
  subsets: ["latin", "latin-ext"],
});

// todo: maintain seo issues
export const metadata: Metadata = {
  title: "Next.ID",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
