import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.ID</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="nextid-container">
        <header className="nextid-header">
          <h1 className="nextid-title text-assistive">Next.ID</h1>
        </header>
      </main>

      <footer className="nextid-footer">
        
      </footer>
    </div>
  )
}
